### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [KulaginVladimir/FESTIM-SurfaceKinetics-Validation#1]
Hi @KulaginVladimir I would add at least the version of FESTIM that is used. Since it's not yet a released version you can give the commit tag and [associated installation instructions](https://stackoverflow.com/a/13754517) in the README.

Ideally, you would have a environment.yml conda environment file with all the relevant dependencies and you can run this repo in mybinder.org

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin 

> Ideally, you would have a environment.yml conda environment file with all the relevant dependencies and you can run this repo in mybinder.org

Do I have to make Jupyter books for each case to run them in mybinder.org?

**Comment by RemDelaporteMathurin** [comment]
I think you need to have Jupyter notebooks yes

**Comment by RemDelaporteMathurin** [comment]
> Do I have to make Jupyter books for each case to run them in mybinder.org?

Actually I think you can run a terminal in binder

**Comment by KulaginVladimir** [comment]
> Actually I think you can run a terminal in binder

@RemDelaporteMathurin, indeed
