### ISSUE TITLE
Plot styling

### ISSUE THREAD

**Issue by KulaginVladimir** [KulaginVladimir/FESTIM-SurfaceKinetics-Validation#10]
Currently, the plots are made with the default mpl settings. I'd like to discuss the styling of figures to improve their appearance.

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin, for the D in damaged W case. What do you think of making a temporal diagram such as (sorry for the ugly power point sketch):
![image](https://github.com/user-attachments/assets/9763651d-31c2-406e-8eef-898cf6557d41)

We could show only 3 D inventory profiles at t=6h, 48h, 100h. These profiles could be set above the temporal dependence

**Comment by RemDelaporteMathurin** [comment]
This sounds like a great idea! are you planning on providing the other profiles (2.5h, 23h, 30h, 70h) as an appendix or something?

**Comment by KulaginVladimir** [comment]
I don't know. We can discuss. I was thinking of smth like this:
![image](https://github.com/user-attachments/assets/617cd3fb-f2af-4b66-8fc6-4649f883fc7d)

**Comment by RemDelaporteMathurin** [comment]
This is very nice!
