### ISSUE TITLE
Binder for reproducibility?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [KulaginVladimir/FESTIM-SurfaceKinetics-Validation#13]
Would be nice to check if this works in Binder so that anyone can reproduce the cases easily

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin 
I've managed to run all notebooks from the main branch in Binder

**Comment by RemDelaporteMathurin** [comment]
Great! We could add this binder badge in the README then!

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/KulaginVladimir/FESTIM-SurfaceKinetics-Validation/HEAD)

I can make a PR

**Comment by RemDelaporteMathurin** [comment]
There is already a binder badge in the readme..... closing this!

**Comment by KulaginVladimir** [comment]
This one?)
![image](https://github.com/user-attachments/assets/2caacaae-9974-434f-bf1d-9aa2a68d6e6a)
