### ISSUE TITLE
Add depth profile comparisons for damaged W

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [KulaginVladimir/FESTIM-SurfaceKinetics-Validation#4]
![image](https://github.com/user-attachments/assets/4d7e18f5-0054-47e5-b83a-92860acae53f)

It would be nice to also show the comparison with depth profiles 

ping @ehodille

**Comment by KulaginVladimir** [comment]
We need trap distribution. Also, it'd be nice to clarify the trap properties, since D conc. in trap4 and in trap3 do not match MHIMS

**Comment by RemDelaporteMathurin** [comment]
I think we need @ehodille about this

**Comment by RemDelaporteMathurin** [comment]
That's great! The Blue MHIMS curve on the right hand side figure (desorption) doesn't seem to match the black curve on Figure 6 in the paper that we have above though. Maybe it's not exactly the same data?

**Comment by ehodille** [comment]
Indeed, that is very nice.
about the blue dotted line, it is me who messed up the extraction of the data to send them to Vladimir. It looks like that on my side
![image](https://github.com/user-attachments/assets/5ba56db2-e921-4bfa-ba9b-e3f2a684c71b)

**Comment by KulaginVladimir** [comment]
Now, it's fine
![image](https://github.com/user-attachments/assets/9d774de2-0aeb-48f0-8e2b-cea9b3aed52b)
